### ISSUE TITLE
Clear cart issue

### ISSUE THREAD

**Issue by n3verlate** [payplug/payplug-magento2#121]
Hello,

When I'm on the checkout and I choose the credit card payment, the popup appears. But when on my web browser I click on the "back" button, it redirects me to my cart, but empty.

Magento version : 2.4.3

Anyone have this issue ?

Thank's !

**Comment by dan-payplug** [comment]
Hello @Alexandre57370,

In order to help you properly, please contact our support team by creating an issue with the link below :

👉 [Contact our support](https://support.payplug.com/hc/fr/requests/new)

Best regards

**Comment by silversil** [comment]
Any news on this? I have reported this bug months ago via email but haven't received a feedback on this..

**Comment by Alexandre57370** [comment]
> Any news on this? I have reported this bug months ago via email but haven't received a feedback on this..

Apparently this is a native behavior of Magento
