### ISSUE TITLE
Missing CSP for iFrame dalenys

### ISSUE THREAD

**Issue by valentin-debris** [payplug/payplug-magento2#187]
Hi,

When using the payment page with the embedded mode, the payment can't be completed due to a redirection in your process from https://secure.payplug.com/ to https://secure-magenta.dalenys.com/. 

The host "dalenys.com" is not in your CSP which trigger an error in Magento and stop the payment validation.

Regards

**Comment by RicoSolutions** [comment]
Hi there,
This issue doesn't seem related to the plugin.
Please can you write at support@payplug.com and give more details, especially who the merchant is. Please also provide some screenshots.
Best regards
