### ISSUE TITLE
Store credit not refund in case of "Payplug payment was not successfull"

### ISSUE THREAD

**Issue by waelkensy** [payplug/payplug-magento2#188]
Hello, 

There is an issue in your module.

**How to reproduce :**
- Add Store credit to current customer ( exemple 50 )
- Pass an order with a product of price > of 50.
- Pay with store credit and the rest with Payplug
- Use a wrong CB card for trigger cancel order
- constat that the order is cancel and the store credit is not refund

**Expected behavior**

The expected behavior is the refund of the store credit when the order is cancel.

**Comment by lacan1** [comment]
Hello,
The payplug refund is based on the payplug payment. 
We do not manage the store credit on our side. 
You need to refund store credits in another way. It is out of payplug scope. 
Maybe you'll be able to find a solution provided by another module specialized in order cancellation or store credits.
