### ISSUE TITLE
Multi Website feature

### ISSUE THREAD

**Issue by angelflo** [payplug/payplug-magento2#49]
Hi,

We currently try your solution in replacement of our current Ogone provider.
We use multi websites magento2 feature (multiple domains name) and we would like to inject dynamicaly the logo of the corresponding website to the payment page (feature that we've got on ogone magento2 module) ... do you plan to enchance your module with this important feature for merchant who use multi websites ?

Thanks  a lot.

**Comment by juchi** [comment]
Hi,
This feature is not on the roadmap yet.
It's more of a Payplug API feature, currently the Payplug payment page does not support having different layouts for the same client ID.
Regards
