### ISSUE TITLE
Orders stuck with "payment review" status

### ISSUE THREAD

**Issue by jhouedanou** [payplug/payplug-magento2#54]
Hi, we've implemented payplug module on https://sabotyouyou.com.
It's a magento 2.3 installation.
Orders paid with a credit are stuck with a "payment review" option. 
Can tell us how to disable it or fix it ?
thanks

**Comment by ronan-jaffre** [comment]
Hello,
"Payment review" is the order status while the payment notification has not been received.

That could means that the payment notification is not well received.

**Comment by jhouedanou** [comment]
Hello, it has happened again. 
This time the payment was successful then cancelled.
Is there any way to fix it? A patch maybe? It's urgent.

**Comment by dan-payplug** [comment]
I am closing this issue because it has not any recent activity.

**Comment by vberthet** [comment]
Hi @dan-payplug ,

This issue is still present in 4.1.0
When the payment fails if the customer doesn't go back to the store the order is stuck in "payment review"

I suspect that there's no IPN, or it's not handled properly 

This is s real issue stock is kept reserved in that state
