### ISSUE TITLE
Missing 1.9.0 release tag

### ISSUE THREAD

**Issue by gcann-tbd** [payplug/payplug-magento2#58]
Le composer.json indique que le module est en version 1.9.0 sur la branche principale master, mais aucun tag de release n'est disponible. Du coup on ne peut pas faire de mise à jour via composer.
`composer require --update-with-all-dependencies payplug/payplug-magento2:1.9.0`

> => Using version ^1.8 for payplug/payplug-magento2

**Comment by juchi** [comment]
I'll close the issue as the 1.9.0 tag is now available
