### ISSUE TITLE
Support Magento 2.4.0

### ISSUE THREAD

**Issue by owebia** [payplug/payplug-magento2#60]
Hello,

Can you please add support for Magento 2.4.0?

Best Regards,
A.L.

**Comment by donatopirolo** [comment]
same problem for me.
On composer require payplug/payplug-magento2 it returns:
![issue](https://user-images.githubusercontent.com/43311656/91577773-80bd5e80-e949-11ea-8c9b-815cc64408de.jpg)
Was there a solution for this?

**Comment by angelflo** [comment]
same problem here ....

**Comment by juchi** [comment]
Hi there,

Support for Magento 2.4 is on its way and should be available shortly.

**Comment by angelflo** [comment]
Hi,

Any news about a release compatible with M2 v 2.4 ??

Thanks a lot

**Comment by juchi** [comment]
Hi,

This is on the QA side for review. The next release will have 2.4 compatibility.
Unfortunately I cannot give an ETA but it should be a matter of days now.

**Comment by juchi** [comment]
Hi,
The payplug module v1.12 has been released with Magento 2.4 compatibility, you should be able to upgrade.
