### ISSUE TITLE
Implementation GraphQl pour PWA ?

### ISSUE THREAD

**Issue by angelflo** [payplug/payplug-magento2#69]
bonjour,
avez-vous prévu d'integrer l'api GraphQL à votre extension afin de pouvoir utiliser PWA ?
(plus précisément via ScandiPWA qui offre a présent une solution stable avec de nombreux prestataires d'extensions qui rendent leur extension compatible via https://marketplace.scandipwa.com)
merci d'avance

**Comment by dan-payplug** [comment]
Bonjour,

Il n'est pas prévu d'intégrer l'api GraphQL à date

Bien à vous
