### ISSUE TITLE
Bad prices display in simulation

### ISSUE THREAD

**Issue by Letseat-TBD** [payplug/payplug-magento2#72]
When prices are set excluding tax in Magento, simulation use this price instead of including price on simulation.
Seems that's ok on configurable product but not simple without parent.

Adding this in **Controller/Oney/Simulation.php** line 74 :
`$productPrice = $this->taxHelper->getTaxPrice($product, $productPrice, true);`

do the trick for simple, but breaks for configurable.

**Comment by dan-payplug** [comment]
Hello @Letseat-TBD,

Could you make a PR for your request please ?

We will analyse your suggestion :)

Best regards

**Comment by dan-payplug** [comment]
I am closing this issue because too old
